-- Generated by Mocodo 4.3.2

CREATE DATABASE IF NOT EXISTS `Librairie`
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_general_ci
;

USE `Librairie`;

CREATE TABLE AUTEUR (
  PRIMARY KEY (idauteur),
  idauteur   VARCHAR(11) NOT NULL,
  nomauteur  VARCHAR(100),
  anneenais  int,
  anneedeces int
);

CREATE TABLE CLASSIFICATION (
  PRIMARY KEY (iddewey),
  iddewey  varchar(3) NOT NULL,
  nomclass varchar(50)
);

CREATE TABLE CLIENT (
  PRIMARY KEY (idcli),
  idcli      int NOT NULL,
  nomcli     VARCHAR(50),
  prenomcli  VARCHAR(30),
  adressecli VARCHAR(100),
  codepostal VARCHAR(5),
  villecli   VARCHAR(100),
  idmag      VARCHAR(42) NOT NULL
);

CREATE TABLE COMMANDE (
  PRIMARY KEY (numcom),
  numcom    int NOT NULL,
  datecom   date,
  enligne   char(1),
  livraison char(1),
  idcli     int NOT NULL,
  idmag     VARCHAR(42) NOT NULL
);

CREATE TABLE DETAILCOMMANDE (
  PRIMARY KEY (numcom, numlig),
  numcom    int NOT NULL,
  numlig    int NOT NULL,
  qte       int,
  prixvente decimal(6,2),
  isbn      VARCHAR(13) NOT NULL
);

CREATE TABLE DETAILPANIER (
  PRIMARY KEY (idpanier, numlig),
  idpanier  int NOT NULL,
  numlig    int NOT NULL,
  qte       int,
  prixvente decimal(6,2),
  isbn      VARCHAR(13) NOT NULL
);

CREATE TABLE ECRIRE (
  PRIMARY KEY (idauteur, isbn),
  idauteur VARCHAR(11) NOT NULL,
  isbn     VARCHAR(13) NOT NULL
);

CREATE TABLE EDITER (
  PRIMARY KEY (isbn, idedit),
  isbn   VARCHAR(13) NOT NULL,
  idedit int NOT NULL
);

CREATE TABLE EDITEUR (
  PRIMARY KEY (idedit),
  idedit  int NOT NULL,
  nomedit VARCHAR(100)
);

CREATE TABLE LIVRE (
  PRIMARY KEY (isbn),
  isbn      VARCHAR(13) NOT NULL,
  titre     VARCHAR(200),
  nbpages   int,
  datepubli int,
  prix      decimal(6,2)
);

CREATE TABLE MAGASIN (
  PRIMARY KEY (idmag),
  idmag    VARCHAR(42) NOT NULL,
  nommag   VARCHAR(42),
  villemag VARCHAR(42)
);

CREATE TABLE PANIER (
  PRIMARY KEY (idpanier),
  idpanier int NOT NULL,
  idcli    int NOT NULL,
  idmag    VARCHAR(42) NOT NULL,
  UNIQUE (idcli)
);

CREATE TABLE POSSEDER (
  PRIMARY KEY (idmag, isbn),
  idmag VARCHAR(42) NOT NULL,
  isbn  VARCHAR(13) NOT NULL,
  qte   VARCHAR(42)
);

CREATE TABLE THEMES (
  PRIMARY KEY (isbn, iddewey),
  isbn    VARCHAR(13) NOT NULL,
  iddewey varchar(3) NOT NULL
);

CREATE TABLE VENDEUR (
  PRIMARY KEY (idvendeur),
  idvendeur     int NOT NULL,
  nomvendeur    VARCHAR(50),
  prenomvendeur VARCHAR(30),
  idmag         VARCHAR(42) NOT NULL
);

ALTER TABLE CLIENT ADD FOREIGN KEY (idmag) REFERENCES MAGASIN (idmag);

ALTER TABLE COMMANDE ADD FOREIGN KEY (idmag) REFERENCES MAGASIN (idmag);
ALTER TABLE COMMANDE ADD FOREIGN KEY (idcli) REFERENCES CLIENT (idcli);

ALTER TABLE DETAILCOMMANDE ADD FOREIGN KEY (isbn) REFERENCES LIVRE (isbn);
ALTER TABLE DETAILCOMMANDE ADD FOREIGN KEY (numcom) REFERENCES COMMANDE (numcom);

ALTER TABLE DETAILPANIER ADD FOREIGN KEY (isbn) REFERENCES LIVRE (isbn);
ALTER TABLE DETAILPANIER ADD FOREIGN KEY (idpanier) REFERENCES PANIER (idpanier);

ALTER TABLE ECRIRE ADD FOREIGN KEY (isbn) REFERENCES LIVRE (isbn);
ALTER TABLE ECRIRE ADD FOREIGN KEY (idauteur) REFERENCES AUTEUR (idauteur);

ALTER TABLE EDITER ADD FOREIGN KEY (idedit) REFERENCES EDITEUR (idedit);
ALTER TABLE EDITER ADD FOREIGN KEY (isbn) REFERENCES LIVRE (isbn);

ALTER TABLE PANIER ADD FOREIGN KEY (idmag) REFERENCES MAGASIN (idmag);
ALTER TABLE PANIER ADD FOREIGN KEY (idcli) REFERENCES CLIENT (idcli);

ALTER TABLE POSSEDER ADD FOREIGN KEY (isbn) REFERENCES LIVRE (isbn);
ALTER TABLE POSSEDER ADD FOREIGN KEY (idmag) REFERENCES MAGASIN (idmag);

ALTER TABLE THEMES ADD FOREIGN KEY (iddewey) REFERENCES CLASSIFICATION (iddewey);
ALTER TABLE THEMES ADD FOREIGN KEY (isbn) REFERENCES LIVRE (isbn);

ALTER TABLE VENDEUR ADD FOREIGN KEY (idmag) REFERENCES MAGASIN (idmag);